on:
  push:
    branches:
      - master

name: QA_QC_checks

jobs:
  QA_QC_checks:
    # Set the operating system CI assumes
    runs-on: ubuntu-latest

    # All steps in workflow
    steps:
      # Housekeeping: various GA tools, install R, install pandoc
      # (to be able to use RMarkdown)
      - uses: actions/checkout@v3
      
      # Shouldn't need this I think?
      # - name: Install cURL Headers
      #   run: sudo apt-get install libcurl4-openssl-dev
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true #use R Studio Package Manager to speed up install
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 3

# Create data outputs from data_raw
      - name: Run data cleaning scripts
        id: create_master_csv
        run: |
          source("01_clean_survey_data.R")
        shell: Rscript {0}     

# knit data validation report
      - name: Generate report
        id: generate_error_reports
        run: Rscript -e 'rmarkdown::render("docs/survey_validation.Rmd")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -a -m 'Ran cleaning script and rendered survey_validation.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          
